name: 'segment'
version: '0.0.1'

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file

#profile: 'default'  # <-- change this as necessary for your setup.

profile: "create your own profile here"  # remove this when pushing to repo.

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"] 

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


models:  
  segment:
    enable: true
    materialized: view
    analytics:
      materialized: view
    utility_models:
      materialized: view
    adwords:
      enable: false
      vars:
        "segment.adwords.campaign_performance_report": "adwords.campaign_performance_report"
    base:
      materialized: view
      vars:
        "base.pages" : "segment.pages"
        "base.tracks" : "segment.tracks"
        "base.users" : "segment.users"
        "base.identifies" : "segment.identifies"

repositories:
  - https://github.com/jgooly/segment
