segment_universal_user_id:
    constraints:
        not_null:
            - universal_alias
            - alias
        unique:
            - alias

segment_sessions:
  constraints:
    unique:
      - session_id
      - ('session_id' || '|' || session_sequence)
    not_null:
      - next_session_start
      - session_sequence
      - session_id

segment_sessions_map:
  constraints:
    unique:
      - ('session_id' || '|' || 'action_sequence')
    not_null:
      - session_id
